import type { FeedGroup } from '~/types/feed'
import { getFavicon, getGhAvatar, getGhIcon } from './utils/img'

export default [
	{
		name: '推荐博客',
		entries: [
			{
				author: '纸鹿本鹿',
				sitenick: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				avatar: 'https://cdn.jsdelivr.net/gh/mcyzsx/picx-images-hosting@master/links/image.8ok4l9tqge.webp',
				date: '2025-09-03',
				qrcode: 'https://cdn.atao.cyou/Web/qrcode_zhilu.png',
				recommend: true,
			},
			{
				author: 'ATao',
				sitenick: 'ATao-Blog',
				desc: '做自己喜欢的事',
				link: 'https://blog.atao.cyou',
				avatar: 'https://cdn.atao.cyou/Web/Avatar.png',
				qrcode: 'https://cdn.jsdelivr.net/gh/mcyzsx/picx-images-hosting@master/links/atao.1hsn7l8mie.webp',
				date: '2025-09-09',
				recommend: true,
			},
			{
				author: 'Matsuzaka Yuki',
				sitenick: '松坂日记',
				desc: 'The world is big, you have to go and see',
				link: 'https://blog.mysqil.com',
				avatar: 'https://blog.mysqil.com/_astro/avatar.D239-k4C_ZU0B2r.webp',
				qrcode: 'https://cdn.jsdelivr.net/gh/mcyzsx/picx-images-hosting@master/links/mizuki-link.webp',
				date: '2025-11-23',
				recommend: true,
			},
			{
				author: 'Xiaozhang',
				sitenick: 'RyuChan',
				desc: 'Ciallo～(∠・ω<)⌒★',
				link: 'https://hub.xiaozhangya.xin',
				avatar: 'https://hub.xiaozhangya.xin/profile.png',
				qrcode: 'https://cdn.jsdelivr.net/gh/mcyzsx/picx-images-hosting@master/links/xiaozhang-link.26lwxg6wy7.webp',
				date: '2025-11-23',
				upstream: true,
			},
			{
				author: '梦爱吃鱼',
				sitenick: '梦爱吃鱼',
				desc: '不负心灵，不负今生。',
				link: 'https://blog.bsgun.cn/',
				avatar: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
				qrcode: 'https://cdn.jsdelivr.net/gh/mcyzsx/picx-images-hosting@master/links/mengaichiyu.webp',
				date: '2025-12-02',
				recommend: true,
			},
			{
				author: '安知鱼',
				sitenick: '安知鱼',
				desc: '生活明朗，万物可爱',
				link: 'https://blog.anheyu.com/',
				avatar: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				qrcode: 'https://cdn.jsdelivr.net/gh/mcyzsx/picx-images-hosting@master/links/anzhiyu-link.webp',
				date: '2025-11-23',
				recommend: true,
			},
			{
				author: '清羽飞扬',
				sitenick: '清羽飞扬',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				avatar: 'https://blog.liushen.fun/info/avatar.ico',
				qrcode: 'https://cdn.jsdelivr.net/gh/mcyzsx/picx-images-hosting@master/links/liushen-link.77dzp14uks.webp',
				date: '2025-11-23',
				recommend: true,
			},
			// 2026-01-10
			{
				author: '张洪Heo',
				sitenick: '张洪Heo',
				desc: '分享设计与科技生活',
				link: 'https://blog.zhheo.com/',
				avatar: 'https://img.zhheo.com/i/67d8fa75943e4.webp',
				qrcode: 'https://cdn.jsdmirror.com/gh/zsxcoder/picx-images-hosting@master/links/links-zhheo.webp',
				date: '2026-01-10',
				recommend: true,
			},
			{
				author: 'CWorld',
				sitenick: 'CWorld Site',
				desc: '求知若愚，虚怀若谷',
				link: 'https://cworld0.com/',
				avatar: 'https://cravatar.cn/avatar/1ffe42aa45a6b1444a786b1f32dfa8aa?s=200',
				qrcode: 'https://cdn.jsdmirror.com/gh/zsxcoder/picx-images-hosting@master/links/links-cworld.webp',
				date: '2026-01-10',
				recommend: true,
			},
			{
				author: '梨尽兴',
				sitenick: '梨尽兴的博客',
				desc: 'A place for peace',
				link: 'https://blog.ljx.icu',
				avatar: 'https://blog.ljx.icu/favicon.png',
				qrcode: 'https://cdn.jsdmirror.com/gh/zsxcoder/picx-images-hosting@master/links/links-ljxme.webp',
				date: '2026-01-10',
				recommend: true,
			},
			// …想加继续往下写
		],
	},
	{
		name: '网上邻居',
		entries: [
			{
				author: 'Cynosura',
				sitenick: 'Cynosura',
				desc: 'Trying to light up the dark.',
				link: 'https://cynosura.one/',
				avatar: 'https://cynosura.one/img/avatar.webp',
				qrcode: 'https://cdn.jsdelivr.net/gh/mcyzsx/picx-images-hosting@master/links/cyno.6t7kdbrnvk.webp',
				date: '2025-12-4',
			},
		],
	},
] satisfies FeedGroup[]
